name: Update dependencies
on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: '34 3 * * */8'

jobs:
  check:
    name: Check for updates
    runs-on: ubuntu-latest
    if: github.repository == 'ohmyzsh/ohmyzsh'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate as @ohmyzsh
        id: generate_token
        uses: ohmyzsh/github-app-token@v2
        with:
          app_id: ${{ secrets.OHMYZSH_APP_ID }}
          private_key: ${{ secrets.OHMYZSH_APP_PRIVATE_KEY }}
      - name: Process dependencies
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          GIT_APP_NAME: ohmyzsh[bot]
          GIT_APP_EMAIL: 54982679+ohmyzsh[bot]@users.noreply.github.com
          TMP_DIR: ${{ runner.temp }}
        run: |
          pip install -r .github/workflows/dependencies/requirements.txt
          python3 .github/workflows/dependencies/updater.py
